//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletos
    {
        public int IDBoleto { get; set; }
        public int IDEvento { get; set; }
        public string NomEvento { get; set; }
        public int NumBoleto { get; set; }
        public int IDPersona { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
